### ISSUE TITLE
Certificates not accepted in FF, Chrome etc

### ISSUE THREAD

**Issue by conradmaaijen** [genesisweb/valet-linux-plus#100]
First thanks for your great work, running fine on my Pop!_os install.

The only think i can't get working are the self-signed certificates.

After a "valet secure" Google Chrome gives the warning "NET::ERR_CERT_AUTHORITY_INVALID"
Firefox returns "The certificate is not trusted because it is self-signed. Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT"

Strange enough Chromium has no problem with the certificated.

Tried to uninstall Firefox, Google Chrome. "valet unsecure" and then "valet secure" but no luck.

Some sites mentions a CA directory with a certificate that i can import in the browser, but there is no CA directory in .valet

Do you have any hints how to get this working?

Thanks.

**Comment by uttamrabadiya** [comment]
@conradmaaijen 
Thank you very much for appreciation! 

Yes we are observing same issue with Firefox, I believe they have changed Certificate Manager ($HOME/.mozilla/firefox/*.default) and because of this it is not working.

We are trying to find better way to whitelist self-signed certificates so that it can work seamlessly.

We will keep you updated once we have some update on this. 

Thank you!

**Comment by conradmaaijen** [comment]
Thanks @uttamrabadiya, 

is was a almost seamless transition from valet on my macbook to valet-linux-plus on Pop!_os :)

**Comment by uttamrabadiya** [comment]
@conradmaaijen 
We've just fixed SSL support for Firefox browser in our latest release (v1.6.7), we are still working to fix it system wide solution.

Thank you!

**Comment by zourite** [comment]
Doesn't work on brave browser
