### ISSUE TITLE
Not swtiching version properly

### ISSUE THREAD

**Issue by MuhammadSaim** [genesisweb/valet-linux-plus#51]
Hi.! I have multiple PHP versions installed on my machine.
![image](https://user-images.githubusercontent.com/19898499/142996480-fd209131-cba3-490b-b0a6-e7682c566c23.png)

Change the PHP version with valet using `valet use 8.0 --update-cli` but this wil just set my cli version but on the FPM version will be the old one or the previous one.

![image](https://user-images.githubusercontent.com/19898499/142996183-af0feeb9-3864-4cfd-8081-8baaecf22668.png)

**Comment by uttamrabadiya** [comment]
@MuhammadSaim Can you describe something more about your system? What is your Operating System, and output of `valet status` command as well.

**Comment by Episodio1** [comment]
Hi! 
I installed valet with php 7.4 running.
Now, when I use "valet use 7.x --update-cli" (7.2 or 7.3) I am not able to run "valet" again because it says:

```
"Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.2.34"

```
If I check my ".config/composer/composer.lock" the only item which requires php >= 7.4 is:

 ```
{
            "name": "psr/container",
            "version": "1.1.2",
            ...
            "require": {
                "php": ">=7.4.0"
           ...
}
```
Is valet using this library "psr/container" or is it there because of another installation??


Thanks.
